name: delta_markdown
version: 0.9.0+1

description: A library for converting between Markdown and Delta of the
  package flutter_quill.
homepage: https://github.com/friebetill/notus_markdown

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  args: ^2.0.0 ## active
  charcode: ^1.3.0 ## inactive
  collection: ^1.15.0 ## active
  flutter_quill: ^7.3.2 ## active

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.16.5
